---
# vars file for bob
BDA_USERNAME: ""
BDA_PASSWORD: ""

INFLUX_DBNAME: ""
INFLUX_USER: ""
INFLUX_PASSWD: ""
INFLUX_MEASUREMENT: "BS12"
INFLUX_HOST: "localhost"
INFLUX_PORT: "8086"

CHANNEL_01_INTERVAL: 45
CHANNEL_05_INTERVAL: 30
CHANNEL_13_INTERVAL: 30
